### ISSUE TITLE
An APM pre-arm check error

### ISSUE THREAD

**Issue by unravelwool** [Hurisa/multi_uav#3]
I ran "`sim_vehicle.py -v ArduCopter -f gazebo-iris --map --console --use-dir uav  -I 0`" in a terminal and it ran fine waiting for the bind of ros.  In other terminal ,I ran "`roslaunch multi_uav environment.launch`". It can run fine at first ,the ardupilot_sitl_gazebo_plugin can bind to ardupilot and the mavproxy console also displayed the link has built. But after a little time,  an error arised in the console and terminal as shown below
```
APM: PreArm: Waiting for Nav Checks
APM: PreArm: gyros still settling
```
And I found you ever asked this error on ardupilot discourse(https://discuss.ardupilot.org/t/how-to-bring-two-instances-of-sim-vehicle-sh/18653/25?u=githublearner-li) but nobody replied to you. 
But I think you maybe have rosolve this error. Could you tell me your solution to this error. Your help will be greatly appreciated！:)

**Comment by Hurisa** [comment]
Might be worth checking your mavproxy version 
`mavproxy.py --v`

it should be output
`MAVProxy Version: 1.6.1`
If it is something else uninstall it and install this version

**Comment by unravelwool** [comment]
I have changed the version of mavproxy to 1.6.1, but it didn't work. When I run `sim_vehicle.py` and `roslaunch multi_uav environment.launch `, the same error still exists.
```
......
Got MAVLink msg: COMMAND_ACK{command: 410, result:4}
**APM: PreArm: Waiting for Nav Checks
APM: PreArm: gyros still settling**
Got MAVLink msg: COMMAND_ACK{command: 410, result:4}
Got MAVLink msg: COMMAND_ACK{command: 410, result:4}
......
```
Is it possible that your environment.launch has some mistakes? Such as the gazebo plugins in the `erlecopter_base.xacro` not setting right or the related topics not match. I don't know exactly what happened when APM conducts pre-arm check. Is something about gyros and imu from gazebo plugins in Gazebo sent to Ardupilot over mavros or over ardupilot_sitl_gazebo_plugin? I am exhausted about this :(. Could you give me a hand?

**Comment by unravelwool** [comment]
hey, Hurisa.
 I have solve this question. The reason is not the version of the mavproxy, but the sensor ros topics subscribed by ardupilot_sitl_gazebo_plugin not corresponding with the sensor ros topics published by sensor plugin in `erlecopter_base.xacro`.  In addition, there is another reason, the empty.world file in multi_uav lacks a gazebo_ros_interface_plugin from Rotors_simulator's rotors_gazebo_plugins folder. This gazebo_ros_interface_plugin can assits the communication between gazebo topics and ros topics. So, add this plugin to empty_world, the pre-arm check can pass!

**Comment by Hurisa** [comment]
Ah! thanks for getting back @unravelwool.
I thought the urdf files in this repo should have already been changed as you mentioned..
But anyway the world file should definetly have the plugin
