### ISSUE TITLE
ERROR:md5sum mismatch

### ISSUE THREAD

**Issue by unravelwool** [Hurisa/multi_uav#4]
Hello, Hurisa.
When I run one erlecopter in a .launch file, I meet this error:
```
[ERROR] [1586269699.974826814, 0.240000000]: md5sum mismatch making local subscription to topic /uav1/erlecopter/command/motor_speed.
[ERROR] [1586269699.974908423, 0.240000000]: Subscriber expects type mav_msgs/Actuators, md5sum 25741daf38ed25442e3a66a855ee8d9c
[ERROR] [1586269699.974928072, 0.240000000]: Publisher provides type mav_msgs/CommandMotorSpeed, md5sum 061082200f78e4ff571a825255200c0d
[ WARN] [1586269699.974941389, 0.240000000]: couldn't register subscriber on topic [/uav1/erlecopter/command/motor_speed]
```
Ardupilot_sitl_gazebo_plugin create a ROS topic named `/uav1/erlecopter/command/motor_speed` to publish motor speed command, and its msg type is `mav_msgs/CommandMotorSpeed`. But this msg type is deprecated and the topic subscriber——gazebo_controller_interface_plugin only accepts the `mav_msgs/Actuators` msg type, the two msg type is different.

Do I have to modify Ardupilot_sitl_gazebo_plugin to change `mav_msgs/CommandMotorSpeed` to `mav_msgs/Actuators` ?
Could you tell me how to fix it ?
the defination of `mav_msgs/CommandMotorSpeed` is like that:
```
Header header
float64[] motor_speed  # motor speed [rad/s]
```
and the defination of `mav_msgs/Actuators` is shown as below:
Header header

```
# This message defines lowest level commands to be sent to the actuator(s). 

float64[] angles             # Angle of the actuator in [rad]. 
                             # E.g. servo angle of a control surface(not angle of the surface!), orientation-angle of a thruster.      
float64[] angular_velocities # Angular velocities of the actuator in [rad/s].
                             # E.g. "rpm" of rotors, propellers, thrusters 
float64[] normalized         # Everything that does not fit the above, normalized between [-1 ... 1
```
I am glad to hearing from you ! :)

yours sincerely 
unravelwool

**Comment by Hurisa** [comment]
Can you arm and take off?

**Comment by unravelwool** [comment]
I can arm and takeoff on APM, but erlecopter's rotors in Gazebo don't rotate. And I run `rostopic echo /uav1/erlecopter/command/motor_speed`, I can see the output data of this topic is correct. I think the reason of rotors not rotating is that the gazebo_controller_interface_plugin can't subcribe to this topic due to the wrong msg type on this topic.

One another question by the way, If I simulate multi-erlecopters in Gazebo, should I add multiple gazebo_ros_interface_plugins mentioned in Issue: "APM: PreArm check error" to the `empty.world` like this:
```
<plugin name="ros_interface_plugin_1" filename="librotors_gazebo_ros_interface_plugin.so"/>
<plugin name="ros_interface_plugin_2" filename="librotors_gazebo_ros_interface_plugin.so"/>
<plugin name="ros_interface_plugin_3" filename="librotors_gazebo_ros_interface_plugin.so"/>
......
```
 Or just one gazebo_ros_interface_plugin is enough?
I'm pleased to hearing your reply :)

**Comment by unravelwool** [comment]
I have modified the ardupilot_sitl_gazebo_plugin.cpp to change the `mav_msgs/CommandMotorSpeed` msg type to `mav_msgs/Actuators` msg type. And it works! 
The process is easy, just set `float64[] angles` and `float64[] normalized` to 0 ,and let each `angular_velocities` data in `mav_msgs/Actuators` be identical with the data of `motor_speed` in `mav_msgs/CommandMotorSpeed`.

with regard to the number of gazebo_ros_interface_plugin in `empty.world`, one is enough, because the topics which have same functionalities in different uavs are created with different name prefixs. It does not cause any confusion. :)
